AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  EchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-go-echo
      PackageType: Zip
      Handler: main.go
      Runtime: go1.x
      CodeUri: ../lambdas/echo
      MemorySize: 128
      Timeout: 30