name: Deploy

on:
  push:
    branches: [main]

jobs:
  setups:
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.KEY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.KEY_AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Check current path
        run: ls -al

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Dependency
        run: go mod tidy -go=1.19

      - name: Build with SAM
        run: sam build

      - name: SAM Package
        run: |
          sam package \
          --template-file ./lambdas/echo/template.yaml \
          --output-template-file package.yaml \
          --s3-bucket lambda-fn-storages

      - name: SAM Deploy
        run: |
          sam deploy \
          --template-file package.yaml \
          --stack-name stackEcho \
          --capabilities CAPABILITY_NAMED_IAM
          --no-confirm-changeset
